anchor_version = "0.24.2"
[features]
seeds = true

[programs.localnet]
serum_remote = "oBRem4fksRF79j3wRkqMHdJfTzxbEEd73JgN3mFQjSK"

[registry]
url = "https://anchor.projectserum.com"

[[test.genesis]]
address = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
program = "tests/deps/raydium_v4.so"

[[test.genesis]]
address = "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX"
program = "tests/deps/open_book_dex.so"

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "tests/seeds/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v.json"

[[test.validator.account]]
address = "8BnEgHoWFysVcuFFX7QztDmzuH8r5ZFvyP3sYwn1XTh6"
filename = "tests/seeds/sol-usdc-open-book/market_state.json"

[[test.validator.account]]
address = "EaXdHx7x3mdGA38j5RSmKYSXMzAFzzUXCLNBEDXDn1d5"
filename = "tests/seeds/sol-usdc-open-book/asks.json"

[[test.validator.account]]
address = "5jWUncPNBMZJ3sTHKmMLszypVkoRK6bfEQMQUHweeQnh"
filename = "tests/seeds/sol-usdc-open-book/bids.json"

[[test.validator.account]]
address = "CPjXDcggXckEq9e4QeXUieVJBpUNpLEmpihLpg5vWjGF"
filename = "tests/seeds/sol-usdc-open-book/request.json"

[[test.validator.account]]
address = "8CvwxZ9Db6XbLD46NZwwmVDZZRDy7eydFcAGkXKh9axa"
filename = "tests/seeds/sol-usdc-open-book/events.json"

[[test.validator.account]]
address = "CKxTHwM9fPMRRvZmFnFoqKNd9pQR21c5Aq9bh5h9oghX"
filename = "tests/seeds/sol-usdc-open-book/base_vault.json"

[[test.validator.account]]
address = "6A5NHCj1yF6urc9wZNe6Bcjj4LVszQNj5DwAWG97yzMu"
filename = "tests/seeds/sol-usdc-open-book/quote_vault.json"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/multiLeggedTrade.ts"

[programs.devnet]
serum_remote = "oBRem4fksRF79j3wRkqMHdJfTzxbEEd73JgN3mFQjSK"
