anchor_version = "0.24.2"
[features]
seeds = true

[programs.localnet]
serum_remote = "oBRem4fksRF79j3wRkqMHdJfTzxbEEd73JgN3mFQjSK"

[registry]
url = "https://anchor.projectserum.com"

[[test.genesis]]
address = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"
program = "tests/deps/serum_dex.so"

[[test.genesis]]
address = "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8"
program = "tests/deps/raydium_v4.so"

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "tests/seeds/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v.json"

[[test.validator.account]]
address = "9wFFyRfZBsuAha4YcuxcXLKwMxJR43S7fPfQLusDBzvT"
filename = "tests/seeds/sol-usdc-serum/market_state.json"

[[test.validator.account]]
address = "CEQdAFKdycHugujQg9k2wbmxjcpdYZyVLfV9WerTnafJ"
filename = "tests/seeds/sol-usdc-serum/asks.json"

[[test.validator.account]]
address = "14ivtgssEBoBjuZJtSAPKYgpUK7DmnSwuPMqJoVTSgKJ"
filename = "tests/seeds/sol-usdc-serum/bids.json"

[[test.validator.account]]
address = "AZG3tFCFtiCqEwyardENBQNpHqxgzbMw8uKeZEw2nRG5"
filename = "tests/seeds/sol-usdc-serum/request.json"

[[test.validator.account]]
address = "5KKsLVU6TcbVDK4BS6K1DGDxnh4Q9xjYJ8XaDCG5t8ht"
filename = "tests/seeds/sol-usdc-serum/events.json"

[[test.validator.account]]
address = "36c6YqAwyGKQG66XEp2dJc5JqjaBNv7sVghEtJv4c7u6"
filename = "tests/seeds/sol-usdc-serum/base_vault.json"

[[test.validator.account]]
address = "8CFo8bL8mZQK8abbFyypFMwEDd8tVJjHTTojMLgQTUSZ"
filename = "tests/seeds/sol-usdc-serum/quote_vault.json"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/multiLeggedTrade.ts"

[programs.devnet]
serum_remote = "oBRem4fksRF79j3wRkqMHdJfTzxbEEd73JgN3mFQjSK"
