anchor_version = "0.24.2"
[features]
seeds = true

[programs.localnet]
serum_remote = "8TJjyzq3iXc48MgV6TD5DumKKwfWKU14Jr9pwgnAbpzs"

[registry]
url = "https://anchor.projectserum.com"

[[test.genesis]]
address = "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX"
program = "tests/deps/serum_dex.so"

[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "tests/seeds/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v.json"

[[test.validator.account]]
address = "9wFFyRfZBsuAha4YcuxcXLKwMxJR43S7fPfQLusDBzvT"
filename = "tests/seeds/sol-usdc-serum/market_state.json"

[[test.validator.account]]
address = "CEQdAFKdycHugujQg9k2wbmxjcpdYZyVLfV9WerTnafJ"
filename = "tests/seeds/sol-usdc-serum/asks.json"

[[test.validator.account]]
address = "14ivtgssEBoBjuZJtSAPKYgpUK7DmnSwuPMqJoVTSgKJ"
filename = "tests/seeds/sol-usdc-serum/bids.json"

[[test.validator.account]]
address = "AZG3tFCFtiCqEwyardENBQNpHqxgzbMw8uKeZEw2nRG5"
filename = "tests/seeds/sol-usdc-serum/request.json"

[[test.validator.account]]
address = "5KKsLVU6TcbVDK4BS6K1DGDxnh4Q9xjYJ8XaDCG5t8ht"
filename = "tests/seeds/sol-usdc-serum/events.json"

[[test.validator.account]]
address = "36c6YqAwyGKQG66XEp2dJc5JqjaBNv7sVghEtJv4c7u6"
filename = "tests/seeds/sol-usdc-serum/base_vault.json"

[[test.validator.account]]
address = "8CFo8bL8mZQK8abbFyypFMwEDd8tVJjHTTojMLgQTUSZ"
filename = "tests/seeds/sol-usdc-serum/quote_vault.json"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[programs.devnet]
serum_remote = "8TJjyzq3iXc48MgV6TD5DumKKwfWKU14Jr9pwgnAbpzs"
